import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
const popins = Poppins({
  weight: ["300", "400", "500", "700"],
});
export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${popins.className} antialiased`}>{children}</body>
    </html>
  );
}
