import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/layouts/Navbar";
import Footer from "@/Components/layouts/Footer";

const popins = Poppins({
  weight: ["300", "400", "500", "700"],
});
export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${popins.className} antialiased`} suppressHydrationWarning>
        <header className="md:w-11/12 py-2 mx-auto">
          <Navbar />
        </header>
        <main className="md:w-11/12 mx-auto py-2">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
